- name: Finalize TML installation
  ansible.builtin.shell:
    cmd: |
      echo "/epics/support/motorTechnosoft/lib/linux-x86_64/" > /etc/ld.so.conf.d/tml.conf && cd && ldconfig
    executable: /bin/bash
    chdir: /usr/local
