- name: Copy tml_lib to assets
  ansible.builtin.shell:
    cmd: |
      mkdir -p /assets/support/technosoft-tml-motor/ && \
      cp -r /epics/support/technosoft-tml-motor/tml_lib /assets/support/technosoft-tml-motor/
    executable: /bin/bash
